In [18]:
import numpy as np

# Create a NumPy array
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Basic slicing
slice1 = arr[2:5]  # Get elements from index 2 to 4
slice2 = arr[:6]   # Get elements from the beginning to index 5
slice3 = arr[7:]   # Get elements from index 7 to the end
slice4 = arr[2:8:2]  # Get elements from index 2 to 7 with a step of 2

# Negative indices
slice5 = arr[-3:]   # Get the last 3 elements
slice6 = arr[:-2]   # Get elements from the beginning to the third-to-last element

# Multi-dimensional array slicing
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

slice_row = arr_2d[1, :]     # Get the second row
slice_col = arr_2d[:, 2]     # Get the third column
slice_subarray = arr_2d[0:2, 1:3]  # Get a subarray
result_dot_product = np.dot(arr_2d, arr_2d)
print("\nPerkalian Matriks (dot product):\n", result_dot_product)

print("\nOriginal array:")
print(arr)
print("\nBasic slicing:")
print(slice1)
print(slice2)
print(slice3)
print(slice4)
print("\nNegative indices:")
print(slice5)
print(slice6)
print("\nMulti-dimensional array slicing:")
print("Original 2D array:")
print(arr_2d)
print("\nSliced row:")
print(slice_row)
print("\nSliced column:")
print(slice_col)
print("\nSliced subarray:")
print(slice_subarray)



Perkalian Matriks (dot product):
 [[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]

Original array:
[0 1 2 3 4 5 6 7 8 9]

Basic slicing:
[2 3 4]
[0 1 2 3 4 5]
[7 8 9]
[2 4 6]

Negative indices:
[7 8 9]
[0 1 2 3 4 5 6 7]

Multi-dimensional array slicing:
Original 2D array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Sliced row:
[4 5 6]

Sliced column:
[3 6 9]

Sliced subarray:
[[2 3]
 [5 6]]


In [14]:
import numpy as np

# Membuat dua array 2D
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

# Penjumlahan dua array
result_addition = array1 + array2
print("Penjumlahan:\n", result_addition)

# Pengurangan dua array
result_subtraction = array1 - array2
print("\nPengurangan:\n", result_subtraction)

# Perkalian dua array (elemen-wise)
result_multiplication = array1 * array2
print("\nPerkalian (elemen-wise):\n", result_multiplication)

# Pembagian dua array (elemen-wise)
result_division = array1 / array2
print("\nPembagian (elemen-wise):\n", result_division)

# Perkalian matriks (dot product)
result_dot_product = np.dot(array1, array2.T)
print("\nPerkalian Matriks (dot product):\n", result_dot_product)


Penjumlahan:
 [[ 8 10 12]
 [14 16 18]]

Pengurangan:
 [[-6 -6 -6]
 [-6 -6 -6]]

Perkalian (elemen-wise):
 [[ 7 16 27]
 [40 55 72]]

Pembagian (elemen-wise):
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]

Perkalian Matriks (dot product):
 [[ 50  68]
 [122 167]]


In [1]:
import numpy as np

# Buat matriks contoh
matrix = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

# Hitung jumlah per baris
sum_per_row = np.sum(matrix, axis=1)
print("Jumlah per baris:", sum_per_row)

# Hitung rata-rata per baris
mean_per_row = np.mean(matrix, axis=1)
print("Rata-rata per baris:", mean_per_row)

# Hitung nilai maksimum per baris
max_per_row = np.max(matrix, axis=1)
print("Nilai maksimum per baris:", max_per_row)


Jumlah per baris: [ 6 15 24]
Rata-rata per baris: [2. 5. 8.]
Nilai maksimum per baris: [3 6 9]


In [4]:
import numpy as np

# Create a 2D array
array_2d = np.array([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])

# Find the maximum value in each row
max_in_each_row = np.max(array_2d, axis=1)
print("Maximum value in each row:", max_in_each_row)

# Find the maximum value in each column
max_in_each_column = np.max(array_2d, axis=0)
print("Maximum value in each column:", max_in_each_column)


Maximum value in each row: [3 6 9]
Maximum value in each column: [7 8 9]


In [6]:
array = np.random.randint(0, 10, 
(3,3))
array

array([[0, 1, 0],
       [0, 6, 8],
       [8, 9, 1]])